/*     */ package de.gerrygames.viarewind.protocol.protocol1_8to1_9.sound;
/*     */ 
/*     */ import java.util.HashMap;
/*     */ 
/*     */ public class SoundRemapper {
/*   6 */   private static final HashMap<Integer, String> sounds1_9 = new HashMap<>();
/*   7 */   private static final HashMap<String, String> sound1_9to1_8 = new HashMap<>();
/*     */   private static int id;
/*     */   
/*     */   private static void register1_9Sound(String sound1_9) {
/*  11 */     sounds1_9.put(Integer.valueOf(id++), sound1_9);
/*     */   }
/*     */   
/*     */   private static void registerSoundRemapping(String sound1_9, String sound1_8) {
/*  15 */     sound1_9to1_8.put(sound1_9, sound1_8);
/*     */   }
/*     */   
/*     */   public static String oldNameFromId(int id) {
/*  19 */     String sound1_9 = sounds1_9.get(Integer.valueOf(id));
/*  20 */     if (sound1_9 == null) return null; 
/*  21 */     return getOldName(sound1_9);
/*     */   }
/*     */   
/*     */   public static String getOldName(String sound1_9) {
/*  25 */     return sound1_9to1_8.getOrDefault(sound1_9, sound1_9);
/*     */   }
/*     */   
/*     */   static {
/*  29 */     registerSoundRemapping("entity.zombie_horse.ambient", "mob.horse.zombie.idle");
/*  30 */     registerSoundRemapping("block.note.snare", "note.snare");
/*  31 */     registerSoundRemapping("block.wood_button.click_off", "random.wood_click");
/*  32 */     registerSoundRemapping("block.wood_button.click_on", "random.wood_click");
/*  33 */     registerSoundRemapping("block.gravel.break", "dig.gravel");
/*  34 */     registerSoundRemapping("block.gravel.place", "dig.gravel");
/*  35 */     registerSoundRemapping("entity.arrow.hit", "random.bowhit");
/*  36 */     registerSoundRemapping("block.tripwire.detach", "random.bowhit");
/*  37 */     registerSoundRemapping("entity.splash_potion.break", "dig.glass");
/*  38 */     registerSoundRemapping("block.glass.break", "dig.glass");
/*  39 */     registerSoundRemapping("entity.zombie.ambient", "mob.zombie.say");
/*  40 */     registerSoundRemapping("entity.zombie_villager.ambient", "mob.zombie.say");
/*  41 */     registerSoundRemapping("entity.pig.death", "mob.pig.death");
/*  42 */     registerSoundRemapping("entity.mule.hurt", "mob.horse.donkey.hit");
/*  43 */     registerSoundRemapping("entity.donkey.hurt", "mob.horse.donkey.hit");
/*  44 */     registerSoundRemapping("entity.endermen.ambient", "mob.endermen.idle");
/*  45 */     registerSoundRemapping("block.portal.ambient", "portal.portal");
/*  46 */     registerSoundRemapping("entity.generic.burn", "random.fizz");
/*  47 */     registerSoundRemapping("block.fire.extinguish", "random.fizz");
/*  48 */     registerSoundRemapping("block.redstone_torch.burnout", "random.fizz");
/*  49 */     registerSoundRemapping("block.lava.extinguish", "random.fizz");
/*  50 */     registerSoundRemapping("entity.generic.extinguish_fire", "random.fizz");
/*  51 */     registerSoundRemapping("block.note.harp", "note.harp");
/*  52 */     registerSoundRemapping("block.snow.hit", "step.snow");
/*  53 */     registerSoundRemapping("block.snow.fall", "step.snow");
/*  54 */     registerSoundRemapping("block.snow.step", "step.snow");
/*  55 */     registerSoundRemapping("entity.arrow.hit_player", "random.successful_hit");
/*  56 */     registerSoundRemapping("entity.zombie_pig.hurt", "mob.zombiepig.zpighurt");
/*  57 */     registerSoundRemapping("entity.wolf.howl", "mob.wolf.howl");
/*  58 */     registerSoundRemapping("entity.firework.launch", "fireworks.launch");
/*  59 */     registerSoundRemapping("entity.cow.hurt", "mob.cow.hurt");
/*  60 */     registerSoundRemapping("entity.cow.death", "mob.cow.hurt");
/*  61 */     registerSoundRemapping("entity.firework.large_blast", "fireworks.largeBlast");
/*  62 */     registerSoundRemapping("entity.blaze.hurt", "mob.blaze.hit");
/*  63 */     registerSoundRemapping("entity.villager.death", "mob.villager.death");
/*  64 */     registerSoundRemapping("entity.blaze.death", "mob.blaze.death");
/*  65 */     registerSoundRemapping("entity.zombie_horse.death", "mob.horse.zombie.death");
/*  66 */     registerSoundRemapping("entity.silverfish.death", "mob.silverfish.kill");
/*  67 */     registerSoundRemapping("entity.endermite.death", "mob.silverfish.kill");
/*  68 */     registerSoundRemapping("record.ward", "records.ward");
/*  69 */     registerSoundRemapping("entity.wolf.pant", "mob.wolf.panting");
/*  70 */     registerSoundRemapping("block.metal.break", "dig.stone");
/*  71 */     registerSoundRemapping("block.metal.place", "dig.stone");
/*  72 */     registerSoundRemapping("entity.armorstand.place", "dig.stone");
/*  73 */     registerSoundRemapping("block.stone.break", "dig.stone");
/*  74 */     registerSoundRemapping("block.stone.place", "dig.stone");
/*  75 */     registerSoundRemapping("block.anvil.break", "dig.stone");
/*  76 */     registerSoundRemapping("block.glass.place", "dig.stone");
/*  77 */     registerSoundRemapping("entity.endermen.stare", "mob.endermen.stare");
/*  78 */     registerSoundRemapping("entity.small_magmacube.hurt", "mob.slime.small");
/*  79 */     registerSoundRemapping("block.slime.fall", "mob.slime.small");
/*  80 */     registerSoundRemapping("entity.small_slime.death", "mob.slime.small");
/*  81 */     registerSoundRemapping("block.slime.step", "mob.slime.small");
/*  82 */     registerSoundRemapping("entity.small_magmacube.death", "mob.slime.small");
/*  83 */     registerSoundRemapping("entity.small_slime.hurt", "mob.slime.small");
/*  84 */     registerSoundRemapping("block.slime.hit", "mob.slime.small");
/*  85 */     registerSoundRemapping("music.nether", "music.game.nether");
/*  86 */     registerSoundRemapping("entity.ghast.death", "mob.ghast.death");
/*  87 */     registerSoundRemapping("entity.guardian.attack", "mob.guardian.attack");
/*  88 */     registerSoundRemapping("block.dispenser.fail", "random.click");
/*  89 */     registerSoundRemapping("block.comparator.click", "random.click");
/*  90 */     registerSoundRemapping("block.stone_button.click_on", "random.click");
/*  91 */     registerSoundRemapping("block.stone_button.click_off", "random.click");
/*  92 */     registerSoundRemapping("block.tripwire.click_on", "random.click");
/*  93 */     registerSoundRemapping("block.dispenser.dispense", "random.click");
/*  94 */     registerSoundRemapping("ui.button.click", "random.click");
/*  95 */     registerSoundRemapping("block.lever.click", "random.click");
/*  96 */     registerSoundRemapping("block.tripwire.attach", "random.click");
/*  97 */     registerSoundRemapping("block.stone_pressureplate.click_on", "random.click");
/*  98 */     registerSoundRemapping("block.wood_pressureplate.click_off", "random.click");
/*  99 */     registerSoundRemapping("block.stone_pressureplate.click_off", "random.click");
/* 100 */     registerSoundRemapping("block.metal_pressureplate.click_off", "random.click");
/* 101 */     registerSoundRemapping("block.tripwire.click_off", "random.click");
/* 102 */     registerSoundRemapping("block.metal_pressureplate.click_on", "random.click");
/* 103 */     registerSoundRemapping("block.wood_pressureplate.click_on", "random.click");
/* 104 */     registerSoundRemapping("entity.zombie_pig.ambient", "mob.zombiepig.zpig");
/* 105 */     registerSoundRemapping("music.dragon", "music.game.end.dragon");
/* 106 */     registerSoundRemapping("entity.firework.twinkle_far", "fireworks.twinkle_far");
/* 107 */     registerSoundRemapping("entity.elder_guardian.ambient_land", "mob.guardian.land.idle");
/* 108 */     registerSoundRemapping("entity.guardian.ambient_land", "mob.guardian.land.idle");
/* 109 */     registerSoundRemapping("block.grass.break", "dig.grass");
/* 110 */     registerSoundRemapping("block.grass.place", "dig.grass");
/* 111 */     registerSoundRemapping("entity.skeleton.step", "mob.skeleton.step");
/* 112 */     registerSoundRemapping("entity.wither.death", "mob.wither.death");
/* 113 */     registerSoundRemapping("entity.wolf.hurt", "mob.wolf.hurt");
/* 114 */     registerSoundRemapping("entity.pig.saddle", "mob.horse.leather");
/* 115 */     registerSoundRemapping("entity.horse.saddle", "mob.horse.leather");
/* 116 */     registerSoundRemapping("entity.bat.loop", "mob.bat.loop");
/* 117 */     registerSoundRemapping("entity.ghast.hurt", "mob.ghast.scream");
/* 118 */     registerSoundRemapping("entity.creeper.death", "mob.creeper.death");
/* 119 */     registerSoundRemapping("entity.horse.gallop", "mob.horse.gallop");
/* 120 */     registerSoundRemapping("entity.wither.spawn", "mob.wither.spawn");
/* 121 */     registerSoundRemapping("entity.endermen.hurt", "mob.endermen.hit");
/* 122 */     registerSoundRemapping("entity.creeper.hurt", "mob.creeper.say");
/* 123 */     registerSoundRemapping("entity.horse.step_wood", "mob.horse.wood");
/* 124 */     registerSoundRemapping("entity.rabbit.death", "mob.rabbit.death");
/* 125 */     registerSoundRemapping("entity.zombie_villager.converted", "mob.zombie.unfect");
/* 126 */     registerSoundRemapping("block.anvil.use", "random.anvil_use");
/* 127 */     registerSoundRemapping("block.enderchest.close", "random.chestclosed");
/* 128 */     registerSoundRemapping("entity.mooshroom.shear", "mob.sheep.shear");
/* 129 */     registerSoundRemapping("entity.sheep.shear", "mob.sheep.shear");
/* 130 */     registerSoundRemapping("entity.item.pickup", "random.pop");
/* 131 */     registerSoundRemapping("entity.bat.death", "mob.bat.death");
/* 132 */     registerSoundRemapping("block.wood.place", "dig.wood");
/* 133 */     registerSoundRemapping("block.wood.break", "dig.wood");
/* 134 */     registerSoundRemapping("block.ladder.place", "dig.wood");
/* 135 */     registerSoundRemapping("entity.armorstand.fall", "dig.wood");
/* 136 */     registerSoundRemapping("block.ladder.break", "dig.wood");
/* 137 */     registerSoundRemapping("record.chirp", "records.chirp");
/* 138 */     registerSoundRemapping("entity.mule.death", "mob.horse.donkey.death");
/* 139 */     registerSoundRemapping("entity.donkey.death", "mob.horse.donkey.death");
/* 140 */     registerSoundRemapping("entity.firework.blast", "fireworks.blast");
/* 141 */     registerSoundRemapping("entity.zombie_pig.angry", "mob.zombiepig.zpigangry");
/* 142 */     registerSoundRemapping("entity.guardian.flop", "mob.guardian.flop");
/* 143 */     registerSoundRemapping("entity.villager.yes", "mob.villager.yes");
/* 144 */     registerSoundRemapping("entity.ghast.warn", "mob.ghast.charge");
/* 145 */     registerSoundRemapping("entity.tnt.primed", "creeper.primed");
/* 146 */     registerSoundRemapping("entity.creeper.primed", "creeper.primed");
/* 147 */     registerSoundRemapping("block.sand.place", "dig.sand");
/* 148 */     registerSoundRemapping("block.sand.break", "dig.sand");
/* 149 */     registerSoundRemapping("entity.chicken.ambient", "mob.chicken.say");
/* 150 */     registerSoundRemapping("record.13", "records.13");
/* 151 */     registerSoundRemapping("record.11", "records.11");
/* 152 */     registerSoundRemapping("entity.elder_guardian.death", "mob.guardian.elder.death");
/* 153 */     registerSoundRemapping("entity.firework.twinkle", "fireworks.twinkle");
/* 154 */     registerSoundRemapping("entity.skeleton_horse.death", "mob.horse.skeleton.death");
/* 155 */     registerSoundRemapping("weather.rain", "ambient.weather.rain");
/* 156 */     registerSoundRemapping("weather.rain.above", "ambient.weather.rain");
/* 157 */     registerSoundRemapping("block.portal.trigger", "portal.trigger");
/* 158 */     registerSoundRemapping("block.enderchest.open", "random.chestopen");
/* 159 */     registerSoundRemapping("entity.horse.land", "mob.horse.land");
/* 160 */     registerSoundRemapping("entity.endermite.step", "mob.silverfish.step");
/* 161 */     registerSoundRemapping("entity.silverfish.step", "mob.silverfish.step");
/* 162 */     registerSoundRemapping("entity.bat.takeoff", "mob.bat.takeoff");
/* 163 */     registerSoundRemapping("entity.villager.no", "mob.villager.no");
/* 164 */     registerSoundRemapping("entity.irongolem.step", "mob.irongolem.walk");
/* 165 */     registerSoundRemapping("block.note.hat", "note.hat");
/* 166 */     registerSoundRemapping("entity.zombie.attack_iron_door", "mob.zombie.metal");
/* 167 */     registerSoundRemapping("entity.villager.trading", "mob.villager.haggle");
/* 168 */     registerSoundRemapping("item.firecharge.use", "mob.ghast.fireball");
/* 169 */     registerSoundRemapping("entity.ghast.shoot", "mob.ghast.fireball");
/* 170 */     registerSoundRemapping("entity.enderdragon.shoot", "mob.ghast.fireball");
/* 171 */     registerSoundRemapping("entity.blaze.shoot", "mob.ghast.fireball");
/* 172 */     registerSoundRemapping("music.credits", "music.game.end.credits");
/* 173 */     registerSoundRemapping("entity.irongolem.death", "mob.irongolem.death");
/* 174 */     registerSoundRemapping("entity.item.break", "random.break");
/* 175 */     registerSoundRemapping("item.shield.break", "random.break");
/* 176 */     registerSoundRemapping("record.mellohi", "records.mellohi");
/* 177 */     registerSoundRemapping("entity.zombie_villager.cure", "mob.zombie.remedy");
/* 178 */     registerSoundRemapping("entity.enderpearl.throw", "random.bow");
/* 179 */     registerSoundRemapping("block.dispenser.launch", "random.bow");
/* 180 */     registerSoundRemapping("entity.skeleton.shoot", "random.bow");
/* 181 */     registerSoundRemapping("entity.endereye.launch", "random.bow");
/* 182 */     registerSoundRemapping("entity.firework.shoot", "random.bow");
/* 183 */     registerSoundRemapping("entity.experience_bottle.throw", "random.bow");
/* 184 */     registerSoundRemapping("entity.snowman.shoot", "random.bow");
/* 185 */     registerSoundRemapping("entity.arrow.shoot", "random.bow");
/* 186 */     registerSoundRemapping("entity.egg.throw", "random.bow");
/* 187 */     registerSoundRemapping("entity.snowball.throw", "random.bow");
/* 188 */     registerSoundRemapping("entity.bobber.throw", "random.bow");
/* 189 */     registerSoundRemapping("entity.lingeringpotion.throw", "random.bow");
/* 190 */     registerSoundRemapping("entity.splash_potion.throw", "random.bow");
/* 191 */     registerSoundRemapping("entity.villager.ambient", "mob.villager.idle");
/* 192 */     registerSoundRemapping("block.cloth.hit", "step.cloth");
/* 193 */     registerSoundRemapping("block.cloth.step", "step.cloth");
/* 194 */     registerSoundRemapping("block.cloth.fall", "step.cloth");
/* 195 */     registerSoundRemapping("entity.silverfish.hurt", "mob.silverfish.hit");
/* 196 */     registerSoundRemapping("entity.endermite.hurt", "mob.silverfish.hit");
/* 197 */     registerSoundRemapping("music.game", "music.game");
/* 198 */     registerSoundRemapping("block.lava.ambient", "liquid.lava");
/* 199 */     registerSoundRemapping("record.mall", "records.mall");
/* 200 */     registerSoundRemapping("entity.blaze.burn", "fire.fire");
/* 201 */     registerSoundRemapping("block.fire.ambient", "fire.fire");
/* 202 */     registerSoundRemapping("entity.zombie.attack_door_wood", "mob.zombie.wood");
/* 203 */     registerSoundRemapping("entity.chicken.step", "mob.chicken.step");
/* 204 */     registerSoundRemapping("record.stal", "records.stal");
/* 205 */     registerSoundRemapping("entity.elder_guardian.hurt_land", "mob.guardian.land.hit");
/* 206 */     registerSoundRemapping("entity.guardian.hurt_land", "mob.guardian.land.hit");
/* 207 */     registerSoundRemapping("entity.chicken.egg", "mob.chicken.plop");
/* 208 */     registerSoundRemapping("entity.donkey.chest", "mob.chicken.plop");
/* 209 */     registerSoundRemapping("entity.enderdragon.flap", "mob.enderdragon.wings");
/* 210 */     registerSoundRemapping("block.grass.step", "step.grass");
/* 211 */     registerSoundRemapping("block.grass.fall", "step.grass");
/* 212 */     registerSoundRemapping("block.grass.hit", "step.grass");
/* 213 */     registerSoundRemapping("entity.horse.breathe", "mob.horse.breathe");
/* 214 */     registerSoundRemapping("entity.mule.ambient", "mob.horse.donkey.idle");
/* 215 */     registerSoundRemapping("entity.donkey.ambient", "mob.horse.donkey.idle");
/* 216 */     registerSoundRemapping("record.far", "records.far");
/* 217 */     registerSoundRemapping("entity.spider.step", "mob.spider.step");
/* 218 */     registerSoundRemapping("entity.cow.ambient", "mob.cow.say");
/* 219 */     registerSoundRemapping("entity.horse.jump", "mob.horse.jump");
/* 220 */     registerSoundRemapping("entity.horse.step", "mob.horse.soft");
/* 221 */     registerSoundRemapping("entity.guardian.hurt", "mob.guardian.hit");
/* 222 */     registerSoundRemapping("entity.enderdragon.death", "mob.enderdragon.end");
/* 223 */     registerSoundRemapping("entity.zombie_villager.step", "mob.zombie.step");
/* 224 */     registerSoundRemapping("entity.zombie.step", "mob.zombie.step");
/* 225 */     registerSoundRemapping("entity.enderdragon.ambient", "mob.enderdragon.growl");
/* 226 */     registerSoundRemapping("entity.enderdragon.growl", "mob.enderdragon.growl");
/* 227 */     registerSoundRemapping("entity.wolf.shake", "mob.wolf.shake");
/* 228 */     registerSoundRemapping("entity.endermen.death", "mob.endermen.death");
/* 229 */     registerSoundRemapping("block.anvil.place", "random.anvil_land");
/* 230 */     registerSoundRemapping("block.anvil.land", "random.anvil_land");
/* 231 */     registerSoundRemapping("entity.minecart.inside", "minecart.inside");
/* 232 */     registerSoundRemapping("entity.slime.squish", "mob.slime.big");
/* 233 */     registerSoundRemapping("entity.magmacube.hurt", "mob.slime.big");
/* 234 */     registerSoundRemapping("entity.magmacube.death", "mob.slime.big");
/* 235 */     registerSoundRemapping("block.slime.break", "mob.slime.big");
/* 236 */     registerSoundRemapping("block.slime.place", "mob.slime.big");
/* 237 */     registerSoundRemapping("entity.slime.jump", "mob.slime.big");
/* 238 */     registerSoundRemapping("entity.slime.hurt", "mob.slime.big");
/* 239 */     registerSoundRemapping("entity.slime.death", "mob.slime.big");
/* 240 */     registerSoundRemapping("block.water.ambient", "liquid.water");
/* 241 */     registerSoundRemapping("entity.pig.hurt", "mob.pig.say");
/* 242 */     registerSoundRemapping("entity.pig.ambient", "mob.pig.say");
/* 243 */     registerSoundRemapping("entity.wither.shoot", "mob.wither.shoot");
/* 244 */     registerSoundRemapping("record.blocks", "records.blocks");
/* 245 */     registerSoundRemapping("item.firecharge.use", "item.fireCharge.use");
/* 246 */     registerSoundRemapping("entity.ghast.shoot", "item.fireCharge.use");
/* 247 */     registerSoundRemapping("entity.enderdragon.shoot", "item.fireCharge.use");
/* 248 */     registerSoundRemapping("entity.blaze.shoot", "item.fireCharge.use");
/* 249 */     registerSoundRemapping("block.sand.hit", "step.sand");
/* 250 */     registerSoundRemapping("block.sand.step", "step.sand");
/* 251 */     registerSoundRemapping("block.sand.fall", "step.sand");
/* 252 */     registerSoundRemapping("music.creative", "music.game.creative");
/* 253 */     registerSoundRemapping("entity.irongolem.hurt", "mob.irongolem.hit");
/* 254 */     registerSoundRemapping("entity.horse.death", "mob.horse.death");
/* 255 */     registerSoundRemapping("entity.bat.hurt", "mob.bat.hurt");
/* 256 */     registerSoundRemapping("entity.ghast.scream", "mob.ghast.affectionate_scream");
/* 257 */     registerSoundRemapping("entity.elder_guardian.ambient", "mob.guardian.elder.idle");
/* 258 */     registerSoundRemapping("entity.zombie_pig.death", "mob.zombiepig.zpigdeath");
/* 259 */     registerSoundRemapping("entity.lightning.thunder", "ambient.weather.thunder");
/* 260 */     registerSoundRemapping("entity.minecart.riding", "minecart.base");
/* 261 */     registerSoundRemapping("block.ladder.step", "step.ladder");
/* 262 */     registerSoundRemapping("block.ladder.fall", "step.ladder");
/* 263 */     registerSoundRemapping("block.ladder.hit", "step.ladder");
/* 264 */     registerSoundRemapping("entity.donkey.angry", "mob.horse.donkey.angry");
/* 265 */     registerSoundRemapping("ambient.cave", "ambient.cave.cave");
/* 266 */     registerSoundRemapping("record.wait", "records.wait");
/* 267 */     registerSoundRemapping("entity.firework.blast_far", "fireworks.blast_far");
/* 268 */     registerSoundRemapping("entity.generic.drink", "random.drink");
/* 269 */     registerSoundRemapping("music.menu", "music.menu");
/* 270 */     registerSoundRemapping("entity.cat.hiss", "mob.cat.hiss");
/* 271 */     registerSoundRemapping("block.note.basedrum", "note.bd");
/* 272 */     registerSoundRemapping("entity.spider.ambient", "mob.spider.say");
/* 273 */     registerSoundRemapping("entity.spider.hurt", "mob.spider.say");
/* 274 */     registerSoundRemapping("block.stone.fall", "step.stone");
/* 275 */     registerSoundRemapping("block.anvil.fall", "step.stone");
/* 276 */     registerSoundRemapping("block.metal.step", "step.stone");
/* 277 */     registerSoundRemapping("block.stone.hit", "step.stone");
/* 278 */     registerSoundRemapping("block.glass.fall", "step.stone");
/* 279 */     registerSoundRemapping("block.stone.step", "step.stone");
/* 280 */     registerSoundRemapping("block.anvil.step", "step.stone");
/* 281 */     registerSoundRemapping("block.metal.hit", "step.stone");
/* 282 */     registerSoundRemapping("block.glass.step", "step.stone");
/* 283 */     registerSoundRemapping("block.metal.fall", "step.stone");
/* 284 */     registerSoundRemapping("block.glass.hit", "step.stone");
/* 285 */     registerSoundRemapping("block.anvil.hit", "step.stone");
/* 286 */     registerSoundRemapping("entity.player.levelup", "random.levelup");
/* 287 */     registerSoundRemapping("block.lava.pop", "liquid.lavapop");
/* 288 */     registerSoundRemapping("entity.sheep.hurt", "mob.sheep.say");
/* 289 */     registerSoundRemapping("entity.sheep.death", "mob.sheep.say");
/* 290 */     registerSoundRemapping("entity.sheep.ambient", "mob.sheep.say");
/* 291 */     registerSoundRemapping("entity.skeleton.ambient", "mob.skeleton.say");
/* 292 */     registerSoundRemapping("entity.blaze.ambient", "mob.blaze.breathe");
/* 293 */     registerSoundRemapping("entity.bat.ambient", "mob.bat.idle");
/* 294 */     registerSoundRemapping("entity.magmacube.squish", "mob.magmacube.big");
/* 295 */     registerSoundRemapping("entity.horse.ambient", "mob.horse.idle");
/* 296 */     registerSoundRemapping("entity.zombie_horse.hurt", "mob.horse.zombie.hit");
/* 297 */     registerSoundRemapping("entity.irongolem.attack", "mob.irongolem.throw");
/* 298 */     registerSoundRemapping("block.cloth.break", "dig.cloth");
/* 299 */     registerSoundRemapping("block.cloth.place", "dig.cloth");
/* 300 */     registerSoundRemapping("block.gravel.fall", "step.gravel");
/* 301 */     registerSoundRemapping("block.gravel.step", "step.gravel");
/* 302 */     registerSoundRemapping("block.gravel.hit", "step.gravel");
/* 303 */     registerSoundRemapping("entity.endermite.ambient", "mob.silverfish.say");
/* 304 */     registerSoundRemapping("entity.silverfish.ambient", "mob.silverfish.say");
/* 305 */     registerSoundRemapping("entity.cat.purr", "mob.cat.purr");
/* 306 */     registerSoundRemapping("entity.zombie.infect", "mob.zombie.infect");
/* 307 */     registerSoundRemapping("entity.generic.eat", "random.eat");
/* 308 */     registerSoundRemapping("entity.wolf.ambient", "mob.wolf.bark");
/* 309 */     registerSoundRemapping("entity.tnt.primed", "game.tnt.primed");
/* 310 */     registerSoundRemapping("entity.creeper.primed", "game.tnt.primed");
/* 311 */     registerSoundRemapping("entity.sheep.step", "mob.sheep.step");
/* 312 */     registerSoundRemapping("entity.zombie_villager.death", "mob.zombie.death");
/* 313 */     registerSoundRemapping("entity.zombie.death", "mob.zombie.death");
/* 314 */     registerSoundRemapping("entity.shulker.teleport", "mob.endermen.portal");
/* 315 */     registerSoundRemapping("item.chorus_fruit.teleport", "mob.endermen.portal");
/* 316 */     registerSoundRemapping("entity.endermen.teleport", "mob.endermen.portal");
/* 317 */     registerSoundRemapping("entity.horse.angry", "mob.horse.angry");
/* 318 */     registerSoundRemapping("entity.wolf.growl", "mob.wolf.growl");
/* 319 */     registerSoundRemapping("block.snow.break", "dig.snow");
/* 320 */     registerSoundRemapping("block.snow.place", "dig.snow");
/* 321 */     registerSoundRemapping("block.piston.extend", "tile.piston.out");
/* 322 */     registerSoundRemapping("entity.player.burp", "random.burp");
/* 323 */     registerSoundRemapping("entity.cow.step", "mob.cow.step");
/* 324 */     registerSoundRemapping("entity.wither.hurt", "mob.wither.hurt");
/* 325 */     registerSoundRemapping("entity.guardian.death_land", "mob.guardian.land.death");
/* 326 */     registerSoundRemapping("entity.elder_guardian.death_land", "mob.guardian.land.death");
/* 327 */     registerSoundRemapping("music.end", "music.game.end");
/* 328 */     registerSoundRemapping("entity.chicken.hurt", "mob.chicken.hurt");
/* 329 */     registerSoundRemapping("entity.chicken.death", "mob.chicken.hurt");
/* 330 */     registerSoundRemapping("entity.wolf.step", "mob.wolf.step");
/* 331 */     registerSoundRemapping("entity.wolf.death", "mob.wolf.death");
/* 332 */     registerSoundRemapping("entity.wolf.whine", "mob.wolf.whine");
/* 333 */     registerSoundRemapping("block.note.pling", "note.pling");
/* 334 */     registerSoundRemapping("entity.rabbit.hurt", "mob.rabbit.hurt");
/* 335 */     registerSoundRemapping("entity.cat.purreow", "mob.cat.purreow");
/* 336 */     registerSoundRemapping("entity.firework.large_blast_far", "fireworks.largeBlast_far");
/* 337 */     registerSoundRemapping("entity.skeleton.hurt", "mob.skeleton.hurt");
/* 338 */     registerSoundRemapping("entity.spider.death", "mob.spider.death");
/* 339 */     registerSoundRemapping("block.anvil.destroy", "random.anvil_break");
/* 340 */     registerSoundRemapping("record.cat", "records.cat");
/* 341 */     registerSoundRemapping("entity.wither.ambient", "mob.wither.idle");
/* 342 */     registerSoundRemapping("entity.elder_guardian.hurt", "mob.guardian.elder.hit");
/* 343 */     registerSoundRemapping("entity.endermen.scream", "mob.endermen.scream");
/* 344 */     registerSoundRemapping("entity.cat.death", "mob.cat.hitt");
/* 345 */     registerSoundRemapping("entity.cat.hurt", "mob.cat.hitt");
/* 346 */     registerSoundRemapping("entity.small_magmacube.squish", "mob.magmacube.small");
/* 347 */     registerSoundRemapping("item.flintandsteel.use", "fire.ignite");
/* 348 */     registerSoundRemapping("entity.enderdragon.hurt", "mob.enderdragon.hit");
/* 349 */     registerSoundRemapping("entity.zombie.hurt", "mob.zombie.hurt");
/* 350 */     registerSoundRemapping("entity.zombie_villager.hurt", "mob.zombie.hurt");
/* 351 */     registerSoundRemapping("entity.enderdragon_fireball.explode", "random.explode");
/* 352 */     registerSoundRemapping("entity.generic.explode", "random.explode");
/* 353 */     registerSoundRemapping("entity.lightning.impact", "random.explode");
/* 354 */     registerSoundRemapping("block.end_gateway.spawn", "random.explode");
/* 355 */     registerSoundRemapping("entity.slime.attack", "mob.slime.attack");
/* 356 */     registerSoundRemapping("entity.magmacube.jump", "mob.magmacube.jump");
/* 357 */     registerSoundRemapping("entity.bobber.splash", "random.splash");
/* 358 */     registerSoundRemapping("entity.skeleton_horse.hurt", "mob.horse.skeleton.hit");
/* 359 */     registerSoundRemapping("entity.rabbit.jump", "mob.rabbit.hop");
/* 360 */     registerSoundRemapping("entity.ghast.ambient", "mob.ghast.moan");
/* 361 */     registerSoundRemapping("entity.elder_guardian.curse", "mob.guardian.curse");
/* 362 */     registerSoundRemapping("entity.splash_potion.break", "game.potion.smash");
/* 363 */     registerSoundRemapping("block.glass.break", "game.potion.smash");
/* 364 */     registerSoundRemapping("block.note.bass", "note.bassattack");
/* 365 */     registerSoundRemapping("block.dispenser.fail", "gui.button.press");
/* 366 */     registerSoundRemapping("block.comparator.click", "gui.button.press");
/* 367 */     registerSoundRemapping("block.stone_button.click_on", "gui.button.press");
/* 368 */     registerSoundRemapping("block.stone_button.click_off", "gui.button.press");
/* 369 */     registerSoundRemapping("block.tripwire.click_on", "gui.button.press");
/* 370 */     registerSoundRemapping("block.dispenser.dispense", "gui.button.press");
/* 371 */     registerSoundRemapping("ui.button.click", "gui.button.press");
/* 372 */     registerSoundRemapping("block.lever.click", "gui.button.press");
/* 373 */     registerSoundRemapping("block.tripwire.attach", "gui.button.press");
/* 374 */     registerSoundRemapping("block.stone_pressureplate.click_on", "gui.button.press");
/* 375 */     registerSoundRemapping("block.wood_pressureplate.click_off", "gui.button.press");
/* 376 */     registerSoundRemapping("block.stone_pressureplate.click_off", "gui.button.press");
/* 377 */     registerSoundRemapping("block.metal_pressureplate.click_off", "gui.button.press");
/* 378 */     registerSoundRemapping("block.tripwire.click_off", "gui.button.press");
/* 379 */     registerSoundRemapping("block.metal_pressureplate.click_on", "gui.button.press");
/* 380 */     registerSoundRemapping("block.wood_pressureplate.click_on", "gui.button.press");
/* 381 */     registerSoundRemapping("entity.experience_orb.touch", "random.orb");
/* 382 */     registerSoundRemapping("entity.experience_orb.pickup", "random.orb");
/* 383 */     registerSoundRemapping("entity.wither.break_block", "mob.zombie.woodbreak");
/* 384 */     registerSoundRemapping("entity.zombie.break_door_wood", "mob.zombie.woodbreak");
/* 385 */     registerSoundRemapping("entity.horse.armor", "mob.horse.armor");
/* 386 */     registerSoundRemapping("entity.rabbit.ambient", "mob.rabbit.idle");
/* 387 */     registerSoundRemapping("block.piston.contract", "tile.piston.in");
/* 388 */     registerSoundRemapping("entity.cat.ambient", "mob.cat.meow");
/* 389 */     registerSoundRemapping("entity.pig.step", "mob.pig.step");
/* 390 */     registerSoundRemapping("record.strad", "records.strad");
/* 391 */     registerSoundRemapping("block.wood.hit", "step.wood");
/* 392 */     registerSoundRemapping("block.wood.fall", "step.wood");
/* 393 */     registerSoundRemapping("block.wood.step", "step.wood");
/* 394 */     registerSoundRemapping("block.portal.travel", "portal.travel");
/* 395 */     registerSoundRemapping("entity.guardian.death", "mob.guardian.death");
/* 396 */     registerSoundRemapping("entity.skeleton.death", "mob.skeleton.death");
/* 397 */     registerSoundRemapping("entity.horse.hurt", "mob.horse.hit");
/* 398 */     registerSoundRemapping("entity.villager.hurt", "mob.villager.hit");
/* 399 */     registerSoundRemapping("entity.skeleton_horse.ambient", "mob.horse.skeleton.idle");
/* 400 */     registerSoundRemapping("block.chest.open", "random.chestopen");
/* 401 */     registerSoundRemapping("block.chest.close", "random.chestclosed");
/* 402 */     registerSoundRemapping("entity.player.hurt_on_fire", "game.player.hurt");
/* 403 */     registerSoundRemapping("entity.player.hurt_drown", "game.player.hurt");
/* 404 */     registerSoundRemapping("entity.generic.swim", "game.neutral.swim");
/* 405 */     registerSoundRemapping("entity.hostile.swim", "game.hostile.swim");
/* 406 */     registerSoundRemapping("entity.player.swim", "game.player.swim");
/* 407 */     registerSoundRemapping("entity.player.splash", "game.player.swim.splash");
/* 408 */     registerSoundRemapping("entity.hostile.splash", "game.hostile.swim.splash");
/* 409 */     registerSoundRemapping("entity.generic.splash", "game.neutral.swim.splash");
/* 410 */     registerSoundRemapping("entity.generic.death", "game.neutral.die");
/* 411 */     registerSoundRemapping("entity.hostile.hurt", "game.hostile.hurt");
/* 412 */     registerSoundRemapping("entity.player.hurt", "game.player.hurt");
/* 413 */     registerSoundRemapping("entity.hostile.death", "game.hostile.die");
/* 414 */     registerSoundRemapping("entity.generic.hurt", "game.neutral.hurt");
/* 415 */     registerSoundRemapping("entity.player.death", "game.player.die");
/* 416 */     registerSoundRemapping("entity.player.big_fall", "game.player.hurt.fall.big");
/* 417 */     registerSoundRemapping("entity.generic.big_fall", "game.neutral.hurt.fall.big");
/* 418 */     registerSoundRemapping("entity.hostile.big_fall", "game.hostile.hurt.fall.big");
/* 419 */     registerSoundRemapping("entity.hostile.small_fall", "game.hostile.hurt.fall.small");
/* 420 */     registerSoundRemapping("entity.player.small_fall", "game.player.hurt.fall.small");
/* 421 */     registerSoundRemapping("entity.generic.small_fall", "game.neutral.hurt.fall.small");
/*     */     
/* 423 */     register1_9Sound("ambient.cave");
/* 424 */     register1_9Sound("block.anvil.break");
/* 425 */     register1_9Sound("block.anvil.destroy");
/* 426 */     register1_9Sound("block.anvil.fall");
/* 427 */     register1_9Sound("block.anvil.hit");
/* 428 */     register1_9Sound("block.anvil.land");
/* 429 */     register1_9Sound("block.anvil.place");
/* 430 */     register1_9Sound("block.anvil.step");
/* 431 */     register1_9Sound("block.anvil.use");
/* 432 */     register1_9Sound("block.brewing_stand.brew");
/* 433 */     register1_9Sound("block.chest.close");
/* 434 */     register1_9Sound("block.chest.locked");
/* 435 */     register1_9Sound("block.chest.open");
/* 436 */     register1_9Sound("block.chorus_flower.death");
/* 437 */     register1_9Sound("block.chorus_flower.grow");
/* 438 */     register1_9Sound("block.cloth.break");
/* 439 */     register1_9Sound("block.cloth.fall");
/* 440 */     register1_9Sound("block.cloth.hit");
/* 441 */     register1_9Sound("block.cloth.place");
/* 442 */     register1_9Sound("block.cloth.step");
/* 443 */     register1_9Sound("block.comparator.click");
/* 444 */     register1_9Sound("block.dispenser.dispense");
/* 445 */     register1_9Sound("block.dispenser.fail");
/* 446 */     register1_9Sound("block.dispenser.launch");
/* 447 */     register1_9Sound("block.end_gateway.spawn");
/* 448 */     register1_9Sound("block.enderchest.close");
/* 449 */     register1_9Sound("block.enderchest.open");
/* 450 */     register1_9Sound("block.fence_gate.close");
/* 451 */     register1_9Sound("block.fence_gate.open");
/* 452 */     register1_9Sound("block.fire.ambient");
/* 453 */     register1_9Sound("block.fire.extinguish");
/* 454 */     register1_9Sound("block.furnace.fire_crackle");
/* 455 */     register1_9Sound("block.glass.break");
/* 456 */     register1_9Sound("block.glass.fall");
/* 457 */     register1_9Sound("block.glass.hit");
/* 458 */     register1_9Sound("block.glass.place");
/* 459 */     register1_9Sound("block.glass.step");
/* 460 */     register1_9Sound("block.grass.break");
/* 461 */     register1_9Sound("block.grass.fall");
/* 462 */     register1_9Sound("block.grass.hit");
/* 463 */     register1_9Sound("block.grass.place");
/* 464 */     register1_9Sound("block.grass.step");
/* 465 */     register1_9Sound("block.gravel.break");
/* 466 */     register1_9Sound("block.gravel.fall");
/* 467 */     register1_9Sound("block.gravel.hit");
/* 468 */     register1_9Sound("block.gravel.place");
/* 469 */     register1_9Sound("block.gravel.step");
/* 470 */     register1_9Sound("block.iron_door.close");
/* 471 */     register1_9Sound("block.iron_door.open");
/* 472 */     register1_9Sound("block.iron_trapdoor.close");
/* 473 */     register1_9Sound("block.iron_trapdoor.open");
/* 474 */     register1_9Sound("block.ladder.break");
/* 475 */     register1_9Sound("block.ladder.fall");
/* 476 */     register1_9Sound("block.ladder.hit");
/* 477 */     register1_9Sound("block.ladder.place");
/* 478 */     register1_9Sound("block.ladder.step");
/* 479 */     register1_9Sound("block.lava.ambient");
/* 480 */     register1_9Sound("block.lava.extinguish");
/* 481 */     register1_9Sound("block.lava.pop");
/* 482 */     register1_9Sound("block.lever.click");
/* 483 */     register1_9Sound("block.metal.break");
/* 484 */     register1_9Sound("block.metal.fall");
/* 485 */     register1_9Sound("block.metal.hit");
/* 486 */     register1_9Sound("block.metal.place");
/* 487 */     register1_9Sound("block.metal.step");
/* 488 */     register1_9Sound("block.metal_pressureplate.click_off");
/* 489 */     register1_9Sound("block.metal_pressureplate.click_on");
/* 490 */     register1_9Sound("block.note.basedrum");
/* 491 */     register1_9Sound("block.note.bass");
/* 492 */     register1_9Sound("block.note.harp");
/* 493 */     register1_9Sound("block.note.hat");
/* 494 */     register1_9Sound("block.note.pling");
/* 495 */     register1_9Sound("block.note.snare");
/* 496 */     register1_9Sound("block.piston.contract");
/* 497 */     register1_9Sound("block.piston.extend");
/* 498 */     register1_9Sound("block.portal.ambient");
/* 499 */     register1_9Sound("block.portal.travel");
/* 500 */     register1_9Sound("block.portal.trigger");
/* 501 */     register1_9Sound("block.redstone_torch.burnout");
/* 502 */     register1_9Sound("block.sand.break");
/* 503 */     register1_9Sound("block.sand.fall");
/* 504 */     register1_9Sound("block.sand.hit");
/* 505 */     register1_9Sound("block.sand.place");
/* 506 */     register1_9Sound("block.sand.step");
/* 507 */     register1_9Sound("block.slime.break");
/* 508 */     register1_9Sound("block.slime.fall");
/* 509 */     register1_9Sound("block.slime.hit");
/* 510 */     register1_9Sound("block.slime.place");
/* 511 */     register1_9Sound("block.slime.step");
/* 512 */     register1_9Sound("block.snow.break");
/* 513 */     register1_9Sound("block.snow.fall");
/* 514 */     register1_9Sound("block.snow.hit");
/* 515 */     register1_9Sound("block.snow.place");
/* 516 */     register1_9Sound("block.snow.step");
/* 517 */     register1_9Sound("block.stone.break");
/* 518 */     register1_9Sound("block.stone.fall");
/* 519 */     register1_9Sound("block.stone.hit");
/* 520 */     register1_9Sound("block.stone.place");
/* 521 */     register1_9Sound("block.stone.step");
/* 522 */     register1_9Sound("block.stone_button.click_off");
/* 523 */     register1_9Sound("block.stone_button.click_on");
/* 524 */     register1_9Sound("block.stone_pressureplate.click_off");
/* 525 */     register1_9Sound("block.stone_pressureplate.click_on");
/* 526 */     register1_9Sound("block.tripwire.attach");
/* 527 */     register1_9Sound("block.tripwire.click_off");
/* 528 */     register1_9Sound("block.tripwire.click_on");
/* 529 */     register1_9Sound("block.tripwire.detach");
/* 530 */     register1_9Sound("block.water.ambient");
/* 531 */     register1_9Sound("block.waterlily.place");
/* 532 */     register1_9Sound("block.wood.break");
/* 533 */     register1_9Sound("block.wood.fall");
/* 534 */     register1_9Sound("block.wood.hit");
/* 535 */     register1_9Sound("block.wood.place");
/* 536 */     register1_9Sound("block.wood.step");
/* 537 */     register1_9Sound("block.wood_button.click_off");
/* 538 */     register1_9Sound("block.wood_button.click_on");
/* 539 */     register1_9Sound("block.wood_pressureplate.click_off");
/* 540 */     register1_9Sound("block.wood_pressureplate.click_on");
/* 541 */     register1_9Sound("block.wooden_door.close");
/* 542 */     register1_9Sound("block.wooden_door.open");
/* 543 */     register1_9Sound("block.wooden_trapdoor.close");
/* 544 */     register1_9Sound("block.wooden_trapdoor.open");
/* 545 */     register1_9Sound("enchant.thorns.hit");
/* 546 */     register1_9Sound("entity.armorstand.break");
/* 547 */     register1_9Sound("entity.armorstand.fall");
/* 548 */     register1_9Sound("entity.armorstand.hit");
/* 549 */     register1_9Sound("entity.armorstand.place");
/* 550 */     register1_9Sound("entity.arrow.hit");
/* 551 */     register1_9Sound("entity.arrow.hit_player");
/* 552 */     register1_9Sound("entity.arrow.shoot");
/* 553 */     register1_9Sound("entity.bat.ambient");
/* 554 */     register1_9Sound("entity.bat.death");
/* 555 */     register1_9Sound("entity.bat.hurt");
/* 556 */     register1_9Sound("entity.bat.loop");
/* 557 */     register1_9Sound("entity.bat.takeoff");
/* 558 */     register1_9Sound("entity.blaze.ambient");
/* 559 */     register1_9Sound("entity.blaze.burn");
/* 560 */     register1_9Sound("entity.blaze.death");
/* 561 */     register1_9Sound("entity.blaze.hurt");
/* 562 */     register1_9Sound("entity.blaze.shoot");
/* 563 */     register1_9Sound("entity.bobber.splash");
/* 564 */     register1_9Sound("entity.bobber.throw");
/* 565 */     register1_9Sound("entity.cat.ambient");
/* 566 */     register1_9Sound("entity.cat.death");
/* 567 */     register1_9Sound("entity.cat.hiss");
/* 568 */     register1_9Sound("entity.cat.hurt");
/* 569 */     register1_9Sound("entity.cat.purr");
/* 570 */     register1_9Sound("entity.cat.purreow");
/* 571 */     register1_9Sound("entity.chicken.ambient");
/* 572 */     register1_9Sound("entity.chicken.death");
/* 573 */     register1_9Sound("entity.chicken.egg");
/* 574 */     register1_9Sound("entity.chicken.hurt");
/* 575 */     register1_9Sound("entity.chicken.step");
/* 576 */     register1_9Sound("entity.cow.ambient");
/* 577 */     register1_9Sound("entity.cow.death");
/* 578 */     register1_9Sound("entity.cow.hurt");
/* 579 */     register1_9Sound("entity.cow.milk");
/* 580 */     register1_9Sound("entity.cow.step");
/* 581 */     register1_9Sound("entity.creeper.death");
/* 582 */     register1_9Sound("entity.creeper.hurt");
/* 583 */     register1_9Sound("entity.creeper.primed");
/* 584 */     register1_9Sound("entity.donkey.ambient");
/* 585 */     register1_9Sound("entity.donkey.angry");
/* 586 */     register1_9Sound("entity.donkey.chest");
/* 587 */     register1_9Sound("entity.donkey.death");
/* 588 */     register1_9Sound("entity.donkey.hurt");
/* 589 */     register1_9Sound("entity.egg.throw");
/* 590 */     register1_9Sound("entity.elder_guardian.ambient");
/* 591 */     register1_9Sound("entity.elder_guardian.ambient_land");
/* 592 */     register1_9Sound("entity.elder_guardian.curse");
/* 593 */     register1_9Sound("entity.elder_guardian.death");
/* 594 */     register1_9Sound("entity.elder_guardian.death_land");
/* 595 */     register1_9Sound("entity.elder_guardian.hurt");
/* 596 */     register1_9Sound("entity.elder_guardian.hurt_land");
/* 597 */     register1_9Sound("entity.enderdragon.ambient");
/* 598 */     register1_9Sound("entity.enderdragon.death");
/* 599 */     register1_9Sound("entity.enderdragon.flap");
/* 600 */     register1_9Sound("entity.enderdragon.growl");
/* 601 */     register1_9Sound("entity.enderdragon.hurt");
/* 602 */     register1_9Sound("entity.enderdragon.shoot");
/* 603 */     register1_9Sound("entity.enderdragon_fireball.explode");
/* 604 */     register1_9Sound("entity.endereye.launch");
/* 605 */     register1_9Sound("entity.endermen.ambient");
/* 606 */     register1_9Sound("entity.endermen.death");
/* 607 */     register1_9Sound("entity.endermen.hurt");
/* 608 */     register1_9Sound("entity.endermen.scream");
/* 609 */     register1_9Sound("entity.endermen.stare");
/* 610 */     register1_9Sound("entity.endermen.teleport");
/* 611 */     register1_9Sound("entity.endermite.ambient");
/* 612 */     register1_9Sound("entity.endermite.death");
/* 613 */     register1_9Sound("entity.endermite.hurt");
/* 614 */     register1_9Sound("entity.endermite.step");
/* 615 */     register1_9Sound("entity.enderpearl.throw");
/* 616 */     register1_9Sound("entity.experience_bottle.throw");
/* 617 */     register1_9Sound("entity.experience_orb.pickup");
/* 618 */     register1_9Sound("entity.experience_orb.touch");
/* 619 */     register1_9Sound("entity.firework.blast");
/* 620 */     register1_9Sound("entity.firework.blast_far");
/* 621 */     register1_9Sound("entity.firework.large_blast");
/* 622 */     register1_9Sound("entity.firework.large_blast_far");
/* 623 */     register1_9Sound("entity.firework.launch");
/* 624 */     register1_9Sound("entity.firework.shoot");
/* 625 */     register1_9Sound("entity.firework.twinkle");
/* 626 */     register1_9Sound("entity.firework.twinkle_far");
/* 627 */     register1_9Sound("entity.generic.big_fall");
/* 628 */     register1_9Sound("entity.generic.burn");
/* 629 */     register1_9Sound("entity.generic.death");
/* 630 */     register1_9Sound("entity.generic.drink");
/* 631 */     register1_9Sound("entity.generic.eat");
/* 632 */     register1_9Sound("entity.generic.explode");
/* 633 */     register1_9Sound("entity.generic.extinguish_fire");
/* 634 */     register1_9Sound("entity.generic.hurt");
/* 635 */     register1_9Sound("entity.generic.small_fall");
/* 636 */     register1_9Sound("entity.generic.splash");
/* 637 */     register1_9Sound("entity.generic.swim");
/* 638 */     register1_9Sound("entity.ghast.ambient");
/* 639 */     register1_9Sound("entity.ghast.death");
/* 640 */     register1_9Sound("entity.ghast.hurt");
/* 641 */     register1_9Sound("entity.ghast.scream");
/* 642 */     register1_9Sound("entity.ghast.shoot");
/* 643 */     register1_9Sound("entity.ghast.warn");
/* 644 */     register1_9Sound("entity.guardian.ambient");
/* 645 */     register1_9Sound("entity.guardian.ambient_land");
/* 646 */     register1_9Sound("entity.guardian.attack");
/* 647 */     register1_9Sound("entity.guardian.death");
/* 648 */     register1_9Sound("entity.guardian.death_land");
/* 649 */     register1_9Sound("entity.guardian.flop");
/* 650 */     register1_9Sound("entity.guardian.hurt");
/* 651 */     register1_9Sound("entity.guardian.hurt_land");
/* 652 */     register1_9Sound("entity.horse.ambient");
/* 653 */     register1_9Sound("entity.horse.angry");
/* 654 */     register1_9Sound("entity.horse.armor");
/* 655 */     register1_9Sound("entity.horse.breathe");
/* 656 */     register1_9Sound("entity.horse.death");
/* 657 */     register1_9Sound("entity.horse.eat");
/* 658 */     register1_9Sound("entity.horse.gallop");
/* 659 */     register1_9Sound("entity.horse.hurt");
/* 660 */     register1_9Sound("entity.horse.jump");
/* 661 */     register1_9Sound("entity.horse.land");
/* 662 */     register1_9Sound("entity.horse.saddle");
/* 663 */     register1_9Sound("entity.horse.step");
/* 664 */     register1_9Sound("entity.horse.step_wood");
/* 665 */     register1_9Sound("entity.hostile.big_fall");
/* 666 */     register1_9Sound("entity.hostile.death");
/* 667 */     register1_9Sound("entity.hostile.hurt");
/* 668 */     register1_9Sound("entity.hostile.small_fall");
/* 669 */     register1_9Sound("entity.hostile.splash");
/* 670 */     register1_9Sound("entity.hostile.swim");
/* 671 */     register1_9Sound("entity.irongolem.attack");
/* 672 */     register1_9Sound("entity.irongolem.death");
/* 673 */     register1_9Sound("entity.irongolem.hurt");
/* 674 */     register1_9Sound("entity.irongolem.step");
/* 675 */     register1_9Sound("entity.item.break");
/* 676 */     register1_9Sound("entity.item.pickup");
/* 677 */     register1_9Sound("entity.itemframe.add_item");
/* 678 */     register1_9Sound("entity.itemframe.break");
/* 679 */     register1_9Sound("entity.itemframe.place");
/* 680 */     register1_9Sound("entity.itemframe.remove_item");
/* 681 */     register1_9Sound("entity.itemframe.rotate_item");
/* 682 */     register1_9Sound("entity.leashknot.break");
/* 683 */     register1_9Sound("entity.leashknot.place");
/* 684 */     register1_9Sound("entity.lightning.impact");
/* 685 */     register1_9Sound("entity.lightning.thunder");
/* 686 */     register1_9Sound("entity.lingeringpotion.throw");
/* 687 */     register1_9Sound("entity.magmacube.death");
/* 688 */     register1_9Sound("entity.magmacube.hurt");
/* 689 */     register1_9Sound("entity.magmacube.jump");
/* 690 */     register1_9Sound("entity.magmacube.squish");
/* 691 */     register1_9Sound("entity.minecart.inside");
/* 692 */     register1_9Sound("entity.minecart.riding");
/* 693 */     register1_9Sound("entity.mooshroom.shear");
/* 694 */     register1_9Sound("entity.mule.ambient");
/* 695 */     register1_9Sound("entity.mule.death");
/* 696 */     register1_9Sound("entity.mule.hurt");
/* 697 */     register1_9Sound("entity.painting.break");
/* 698 */     register1_9Sound("entity.painting.place");
/* 699 */     register1_9Sound("entity.pig.ambient");
/* 700 */     register1_9Sound("entity.pig.death");
/* 701 */     register1_9Sound("entity.pig.hurt");
/* 702 */     register1_9Sound("entity.pig.saddle");
/* 703 */     register1_9Sound("entity.pig.step");
/* 704 */     register1_9Sound("entity.player.attack.crit");
/* 705 */     register1_9Sound("entity.player.attack.knockback");
/* 706 */     register1_9Sound("entity.player.attack.nodamage");
/* 707 */     register1_9Sound("entity.player.attack.strong");
/* 708 */     register1_9Sound("entity.player.attack.sweep");
/* 709 */     register1_9Sound("entity.player.attack.weak");
/* 710 */     register1_9Sound("entity.player.big_fall");
/* 711 */     register1_9Sound("entity.player.breath");
/* 712 */     register1_9Sound("entity.player.burp");
/* 713 */     register1_9Sound("entity.player.death");
/* 714 */     register1_9Sound("entity.player.hurt");
/* 715 */     register1_9Sound("entity.player.levelup");
/* 716 */     register1_9Sound("entity.player.small_fall");
/* 717 */     register1_9Sound("entity.player.splash");
/* 718 */     register1_9Sound("entity.player.swim");
/* 719 */     register1_9Sound("entity.rabbit.ambient");
/* 720 */     register1_9Sound("entity.rabbit.attack");
/* 721 */     register1_9Sound("entity.rabbit.death");
/* 722 */     register1_9Sound("entity.rabbit.hurt");
/* 723 */     register1_9Sound("entity.rabbit.jump");
/* 724 */     register1_9Sound("entity.sheep.ambient");
/* 725 */     register1_9Sound("entity.sheep.death");
/* 726 */     register1_9Sound("entity.sheep.hurt");
/* 727 */     register1_9Sound("entity.sheep.shear");
/* 728 */     register1_9Sound("entity.sheep.step");
/* 729 */     register1_9Sound("entity.shulker.ambient");
/* 730 */     register1_9Sound("entity.shulker.close");
/* 731 */     register1_9Sound("entity.shulker.death");
/* 732 */     register1_9Sound("entity.shulker.hurt");
/* 733 */     register1_9Sound("entity.shulker.hurt_closed");
/* 734 */     register1_9Sound("entity.shulker.open");
/* 735 */     register1_9Sound("entity.shulker.shoot");
/* 736 */     register1_9Sound("entity.shulker.teleport");
/* 737 */     register1_9Sound("entity.shulker_bullet.hit");
/* 738 */     register1_9Sound("entity.shulker_bullet.hurt");
/* 739 */     register1_9Sound("entity.silverfish.ambient");
/* 740 */     register1_9Sound("entity.silverfish.death");
/* 741 */     register1_9Sound("entity.silverfish.hurt");
/* 742 */     register1_9Sound("entity.silverfish.step");
/* 743 */     register1_9Sound("entity.skeleton.ambient");
/* 744 */     register1_9Sound("entity.skeleton.death");
/* 745 */     register1_9Sound("entity.skeleton.hurt");
/* 746 */     register1_9Sound("entity.skeleton.shoot");
/* 747 */     register1_9Sound("entity.skeleton.step");
/* 748 */     register1_9Sound("entity.skeleton_horse.ambient");
/* 749 */     register1_9Sound("entity.skeleton_horse.death");
/* 750 */     register1_9Sound("entity.skeleton_horse.hurt");
/* 751 */     register1_9Sound("entity.slime.attack");
/* 752 */     register1_9Sound("entity.slime.death");
/* 753 */     register1_9Sound("entity.slime.hurt");
/* 754 */     register1_9Sound("entity.slime.jump");
/* 755 */     register1_9Sound("entity.slime.squish");
/* 756 */     register1_9Sound("entity.small_magmacube.death");
/* 757 */     register1_9Sound("entity.small_magmacube.hurt");
/* 758 */     register1_9Sound("entity.small_magmacube.squish");
/* 759 */     register1_9Sound("entity.small_slime.death");
/* 760 */     register1_9Sound("entity.small_slime.hurt");
/* 761 */     register1_9Sound("entity.small_slime.jump");
/* 762 */     register1_9Sound("entity.small_slime.squish");
/* 763 */     register1_9Sound("entity.snowball.throw");
/* 764 */     register1_9Sound("entity.snowman.ambient");
/* 765 */     register1_9Sound("entity.snowman.death");
/* 766 */     register1_9Sound("entity.snowman.hurt");
/* 767 */     register1_9Sound("entity.snowman.shoot");
/* 768 */     register1_9Sound("entity.spider.ambient");
/* 769 */     register1_9Sound("entity.spider.death");
/* 770 */     register1_9Sound("entity.spider.hurt");
/* 771 */     register1_9Sound("entity.spider.step");
/* 772 */     register1_9Sound("entity.splash_potion.break");
/* 773 */     register1_9Sound("entity.splash_potion.throw");
/* 774 */     register1_9Sound("entity.squid.ambient");
/* 775 */     register1_9Sound("entity.squid.death");
/* 776 */     register1_9Sound("entity.squid.hurt");
/* 777 */     register1_9Sound("entity.tnt.primed");
/* 778 */     register1_9Sound("entity.villager.ambient");
/* 779 */     register1_9Sound("entity.villager.death");
/* 780 */     register1_9Sound("entity.villager.hurt");
/* 781 */     register1_9Sound("entity.villager.no");
/* 782 */     register1_9Sound("entity.villager.trading");
/* 783 */     register1_9Sound("entity.villager.yes");
/* 784 */     register1_9Sound("entity.witch.ambient");
/* 785 */     register1_9Sound("entity.witch.death");
/* 786 */     register1_9Sound("entity.witch.drink");
/* 787 */     register1_9Sound("entity.witch.hurt");
/* 788 */     register1_9Sound("entity.witch.throw");
/* 789 */     register1_9Sound("entity.wither.ambient");
/* 790 */     register1_9Sound("entity.wither.break_block");
/* 791 */     register1_9Sound("entity.wither.death");
/* 792 */     register1_9Sound("entity.wither.hurt");
/* 793 */     register1_9Sound("entity.wither.shoot");
/* 794 */     register1_9Sound("entity.wither.spawn");
/* 795 */     register1_9Sound("entity.wolf.ambient");
/* 796 */     register1_9Sound("entity.wolf.death");
/* 797 */     register1_9Sound("entity.wolf.growl");
/* 798 */     register1_9Sound("entity.wolf.howl");
/* 799 */     register1_9Sound("entity.wolf.hurt");
/* 800 */     register1_9Sound("entity.wolf.pant");
/* 801 */     register1_9Sound("entity.wolf.shake");
/* 802 */     register1_9Sound("entity.wolf.step");
/* 803 */     register1_9Sound("entity.wolf.whine");
/* 804 */     register1_9Sound("entity.zombie.ambient");
/* 805 */     register1_9Sound("entity.zombie.attack_door_wood");
/* 806 */     register1_9Sound("entity.zombie.attack_iron_door");
/* 807 */     register1_9Sound("entity.zombie.break_door_wood");
/* 808 */     register1_9Sound("entity.zombie.death");
/* 809 */     register1_9Sound("entity.zombie.hurt");
/* 810 */     register1_9Sound("entity.zombie.infect");
/* 811 */     register1_9Sound("entity.zombie.step");
/* 812 */     register1_9Sound("entity.zombie_horse.ambient");
/* 813 */     register1_9Sound("entity.zombie_horse.death");
/* 814 */     register1_9Sound("entity.zombie_horse.hurt");
/* 815 */     register1_9Sound("entity.zombie_pig.ambient");
/* 816 */     register1_9Sound("entity.zombie_pig.angry");
/* 817 */     register1_9Sound("entity.zombie_pig.death");
/* 818 */     register1_9Sound("entity.zombie_pig.hurt");
/* 819 */     register1_9Sound("entity.zombie_villager.ambient");
/* 820 */     register1_9Sound("entity.zombie_villager.converted");
/* 821 */     register1_9Sound("entity.zombie_villager.cure");
/* 822 */     register1_9Sound("entity.zombie_villager.death");
/* 823 */     register1_9Sound("entity.zombie_villager.hurt");
/* 824 */     register1_9Sound("entity.zombie_villager.step");
/* 825 */     register1_9Sound("item.armor.equip_chain");
/* 826 */     register1_9Sound("item.armor.equip_diamond");
/* 827 */     register1_9Sound("item.armor.equip_generic");
/* 828 */     register1_9Sound("item.armor.equip_gold");
/* 829 */     register1_9Sound("item.armor.equip_iron");
/* 830 */     register1_9Sound("item.armor.equip_leather");
/* 831 */     register1_9Sound("item.bottle.fill");
/* 832 */     register1_9Sound("item.bottle.fill_dragonbreath");
/* 833 */     register1_9Sound("item.bucket.empty");
/* 834 */     register1_9Sound("item.bucket.empty_lava");
/* 835 */     register1_9Sound("item.bucket.fill");
/* 836 */     register1_9Sound("item.bucket.fill_lava");
/* 837 */     register1_9Sound("item.chorus_fruit.teleport");
/* 838 */     register1_9Sound("item.firecharge.use");
/* 839 */     register1_9Sound("item.flintandsteel.use");
/* 840 */     register1_9Sound("item.hoe.till");
/* 841 */     register1_9Sound("item.shield.block");
/* 842 */     register1_9Sound("item.shield.break");
/* 843 */     register1_9Sound("item.shovel.flatten");
/* 844 */     register1_9Sound("music.creative");
/* 845 */     register1_9Sound("music.credits");
/* 846 */     register1_9Sound("music.dragon");
/* 847 */     register1_9Sound("music.end");
/* 848 */     register1_9Sound("music.game");
/* 849 */     register1_9Sound("music.menu");
/* 850 */     register1_9Sound("music.nether");
/* 851 */     register1_9Sound("record.11");
/* 852 */     register1_9Sound("record.13");
/* 853 */     register1_9Sound("record.blocks");
/* 854 */     register1_9Sound("record.cat");
/* 855 */     register1_9Sound("record.chirp");
/* 856 */     register1_9Sound("record.far");
/* 857 */     register1_9Sound("record.mall");
/* 858 */     register1_9Sound("record.mellohi");
/* 859 */     register1_9Sound("record.stal");
/* 860 */     register1_9Sound("record.strad");
/* 861 */     register1_9Sound("record.wait");
/* 862 */     register1_9Sound("record.ward");
/* 863 */     register1_9Sound("ui.button.click");
/* 864 */     register1_9Sound("weather.rain");
/* 865 */     register1_9Sound("weather.rain.above");
/*     */   }
/*     */ }


/* Location:              C:\Users\march\Desktop\Diavlo-client.jar!\de\gerrygames\viarewind\protocol\protocol1_8to1_9\sound\SoundRemapper.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */